name: CI Checks

on: [pull_request]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: "ubuntu-20.04"
    env:
      PYTHONUNBUFFERED: 1
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout RCareWorld repository
        uses: actions/checkout@v4
        with:
          lfs: true 

      - name: Set up Git LFS
        run: git lfs install

      - name: Pull LFS Files
        run: git lfs pull

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rcareworld
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd pyrcareworld
          pip install -r requirements.txt
          pip install -e .
          pip uninstall -y numpy
          conda install numpy
          cd ../

          python3 -m pip install https://github.com/ompl/ompl/releases/download/prerelease/ompl-1.6.0-cp310-cp310-manylinux_2_28_x86_64.whl
          sudo apt-get install libminizip1

      - name: Run unit tests
        run: |
          echo "::group::Running tests"
          pytest --capture=tee-sys tests/
          echo "::endgroup::"    
